name = "cfr2bot"
main = "src/index.ts"
compatibility_date = "2022-05-14"

# wrangler dev/deploy
[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'cfr2bot'
preview_bucket_name ='cfr2bot-dev'

# wrangler dev/deploy --env development
[env.development.vars]
ENCRYPT_SECRET="xxx"

# wrangler dev/deploy --env development
[[env.development.r2_buckets]]
binding = 'BUCKET'
bucket_name = 'cfr2bot'
preview_bucket_name ='cfr2bot-dev'
