name = "r2"
main = "src/index.ts"
compatibility_date = "2022-05-14"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'proselog'
preview_bucket_name ='proselog-dev'

[env.development.vars]
# should set a strong secret in production using wrangler CLI
ENCRYPT_SECRET="xxx"

# Why do I need to set it again? Cloudflare?
[[env.development.r2_buckets]]
binding = 'BUCKET'
bucket_name = 'proselog'
preview_bucket_name ='proselog-dev'